export const CASHFLOW_LIST_REQUEST = "CASHFLOW_LIST_REQUEST";
export const CASHFLOW_LIST_SUCCESS = "CASHFLOW_LIST_SUCCESS";
export const CASHFLOW_LIST_FAIL = "CASHFLOW_LIST_FAIL";

export const CASHFLOW_DELETE_REQUEST = "CASHFLOW_DELETE_REQUEST";
export const CASHFLOW_DELETE_SUCCESS = "CASHFLOW_DELETE_SUCCESS";
export const CASHFLOW_DELETE_FAIL = "CASHFLOW_DELETE_FAIL";