export const MESSAGE_LIST_REQUEST = "MESSAGE_LIST_REQUEST";
export const MESSAGE_LIST_SUCCESS = "MESSAGE_LIST_SUCCESS";
export const MESSAGE_LIST_FAIL = "MESSAGE_LIST_FAIL";

export const MESSAGE_DETAILS_LIST_MY_REQUEST = "MESSAGE_DETAILS_LIST_MY_REQUEST";
export const MESSAGE_DETAILS_LIST_MY_SUCCESS = "MESSAGE_DETAILS_LIST_MY_SUCCESS";
export const MESSAGE_DETAILS_LIST_MY_FAIL = "MESSAGE_DETAILS_LIST_MY_FAIL";
export const MESSAGE_DETAILS_LIST_MY_RESET = "MESSAGE_DETAILSLIST_MY_RESET";


export const MESSAGE_UPDATE_REQUEST = "MESSAGE_UPDATE_REQUEST";
export const MESSAGE_UPDATE_SUCCESS = "MESSAGE_UPDATE_SUCCESS";
export const MESSAGE_UPDATE_FAIL = "MESSAGE_UPDATE_FAIL";
