export const GET_BALANCE_REQUEST = "GET_BALANCE_REQUEST";
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS";
export const GET_BALANCE_FAIL = "GET_BALANCE_FAIL";

export const UPDATE_BALANCE_REQUEST = "UPDATE_BALANCE_REQUEST";
export const UPDATE_BALANCE_SUCCESS = "UPDATE_BALANCE_SUCCESS";
export const UPDATE_BALANCE_FAIL = "UPDATE_BALANCE__FAIL";

export const GETDETAILS_BALANCE_REQUEST = "GETDETAILS_BALANCE_REQUEST";
export const GETDETAILS_BALANCE_SUCCESS = "GETDETAILS_BALANCE_SUCCESS";
export const GETDETAILS_BALANCE_FAIL = "GETDETAILS_BALANCE_FAIL";

export const DELETE_BALANCE_REQUEST = "DELETE_BALANCE_REQUEST";
export const DELETE_BALANCE_SUCCESS = "DELETE_BALANCE_SUCCESS";
export const DELETE_BALANCE_FAIL = "DELETE_BALANCE__FAIL";